name: Update iNews Source URL

on:
  schedule:
    - cron: '0 */3 * * *' # Auto-update setiap 3 jam
  workflow_dispatch:

jobs:
  update-link:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fetch and Extract iNews URL
      run: |
        curl -s "https://raw.githubusercontent.com/apistech/project/refs/heads/main/playlists/rctiplus.m3u" -o rctiplus.m3u
        INEWS_URL=$(grep -A 1 -i "iNews" rctiplus.m3u | grep -v "iNews" | grep "http" | tr -d '\r' | xargs)

        if [ -z "$INEWS_URL" ]; then
          echo "Ralat: URL tidak dijumpai."
          exit 1
        fi

        echo "$INEWS_URL" > inews.txt

    - name: Commit and Push Changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        if git status --porcelain | grep -q "inews.txt"; then
          git add inews.txt
          git commit -m "Update iNews Raw URL: $(date)"
          git push
        else
          echo "Tiada perubahan URL."
        fi
